compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network monadTestnet

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network monadTestnet

verify_Celestial:
	npx hardhat verify --network monadTestnet 0xDE115676F736F154eEF8398A37e4ACB4d61892e6

verify_Gladiator:
	npx hardhat verify --network monadTestnet 0x74Ce2e9ef64018a1f7b1A0F035782045d566ef4f